/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface Cv1pbAmbulanceWlList {
    }
}
declare global {
    interface HTMLCv1pbAmbulanceWlListElement extends Components.Cv1pbAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLCv1pbAmbulanceWlListElement: {
        prototype: HTMLCv1pbAmbulanceWlListElement;
        new (): HTMLCv1pbAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "cv1pb-ambulance-wl-list": HTMLCv1pbAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface Cv1pbAmbulanceWlList {
    }
    interface IntrinsicElements {
        "cv1pb-ambulance-wl-list": Cv1pbAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cv1pb-ambulance-wl-list": LocalJSX.Cv1pbAmbulanceWlList & JSXBase.HTMLAttributes<HTMLCv1pbAmbulanceWlListElement>;
        }
    }
}
